// Package capability contains the transport-neutral capability catalog.
package capability

// Definition describes one reviewed capability route across the CLI and MCP
// transports. An empty MCPTool means that the capability is CLI-only.
type Definition struct {
	ID           string
	TaskClass    string
	Service      string
	Role         string
	Priority     int
	Summary      string
	CLICommand   string
	MCPTool      string
	MCPScope     string
	Evidence     string
	Completeness string
	Skill        string
	Reference    string
}

// definitions is intentionally small and curated. It routes exact agent task
// classes to the shortest reviewed transport route; it is not a fuzzy
// natural-language classifier or a command/tool registry.
var definitions = []Definition{
	{ID: "jira.issue.search", TaskClass: "jira/evidence", Service: "jira", Role: "discover", Priority: 5, Summary: "Search Jira for candidate issues before exact evidence expansion", CLICommand: "jira issue search", MCPTool: "jira_issue_search", MCPScope: "Bounded IssueList page; one selector alias and encoded-result cap.", Evidence: "snapshot", Completeness: "explicit", Skill: "jira", Reference: "reference/evidence-workflow.md"},
	{ID: "jira.issue.fields", TaskClass: "jira/evidence", Service: "jira", Role: "discover", Priority: 10, Summary: "Discover non-empty issue fields with names and compact values", CLICommand: "jira issue fields", Evidence: "qualified", Completeness: "explicit", Skill: "jira", Reference: "reference/evidence-workflow.md"},
	{ID: "jira.epic.digest", TaskClass: "jira/evidence", Service: "jira", Role: "primary", Priority: 20, Summary: "Collect bounded multi-source evidence for one epic and period", CLICommand: "jira epic digest", MCPTool: "jira_epic_digest", MCPScope: "Bounded digest with explicit include sources; no Confluence expansion.", Evidence: "qualified", Completeness: "per-source", Skill: "jira", Reference: "reference/evidence-workflow.md"},
	{ID: "jira.issue.field.get", TaskClass: "jira/evidence", Service: "jira", Role: "expand", Priority: 30, Summary: "Expand one exact clipped field with a hard byte bound", CLICommand: "jira issue field get", MCPTool: "jira_issue_field_get", MCPScope: "Exact compact field evidence with stricter typed byte bound.", Evidence: "qualified", Completeness: "explicit", Skill: "jira", Reference: "reference/evidence-workflow.md"},
	{ID: "jira.issue.refs", TaskClass: "jira/evidence", Service: "jira", Role: "expand", Priority: 40, Summary: "Extract provenance-qualified artifact references", CLICommand: "jira issue refs", MCPTool: "jira_issue_refs", MCPScope: "Summary/counts and source qualification only; no raw URLs, summary, type, or narrative; not a route when references themselves are required.", Evidence: "qualified", Completeness: "per-source", Skill: "jira", Reference: "reference/evidence-workflow.md"},
	{ID: "jira.issue.history", TaskClass: "jira/evidence", Service: "jira", Role: "expand", Priority: 50, Summary: "Read field-filtered changelog evidence within a period", CLICommand: "jira issue history", MCPTool: "jira_issue_history", MCPScope: "Summary projection and selected-field last_changes only; no raw changelog rows; not a route when individual changes are required.", Evidence: "qualified", Completeness: "explicit", Skill: "jira", Reference: "reference/evidence-workflow.md"},

	{ID: "jira.board.list", TaskClass: "jira/portfolio", Service: "jira", Role: "discover", Priority: 10, Summary: "Discover Agile boards and stable identifiers", CLICommand: "jira board list", Evidence: "snapshot", Completeness: "pagination", Skill: "jira", Reference: "reference/portfolio-evidence.md"},
	{ID: "jira.board.view", TaskClass: "jira/portfolio", Service: "jira", Role: "primary", Priority: 20, Summary: "Read normalized board configuration, issues, and backlog", CLICommand: "jira board view", MCPTool: "jira_board_view", MCPScope: "Bounded transient normalized board/backlog snapshot.", Evidence: "snapshot", Completeness: "explicit", Skill: "jira", Reference: "reference/portfolio-evidence.md"},
	{ID: "jira.structure.get", TaskClass: "jira/portfolio", Service: "jira", Role: "discover", Priority: 30, Summary: "Qualify metadata for one exact Structure id before selecting a bounded view", CLICommand: "jira structure get", MCPTool: "jira_structure_get", MCPScope: "Metadata projection limited to id, name, and read-only state.", Evidence: "identity", Completeness: "explicit", Skill: "jira", Reference: "reference/portfolio-evidence.md"},
	{ID: "jira.structure.folders", TaskClass: "jira/portfolio", Service: "jira", Role: "discover", Priority: 40, Summary: "Discover Structure folders before selecting a subtree", CLICommand: "jira structure folders", Evidence: "snapshot", Completeness: "explicit", Skill: "jira", Reference: "reference/portfolio-evidence.md"},
	{ID: "jira.structure.view", TaskClass: "jira/portfolio", Service: "jira", Role: "primary", Priority: 50, Summary: "Read a normalized Structure hierarchy with selected issue fields", CLICommand: "jira structure view", MCPTool: "jira_structure_view", MCPScope: "Normalized bounded hierarchy/subtree with typed fields and optional forest gate.", Evidence: "snapshot", Completeness: "explicit", Skill: "jira", Reference: "reference/portfolio-evidence.md"},
	{ID: "jira.portfolio.epic.digest", TaskClass: "jira/portfolio", Service: "jira", Role: "expand", Priority: 60, Summary: "Qualify only the evidence sources missing from the portfolio snapshot", CLICommand: "jira epic digest", MCPTool: "jira_epic_digest", MCPScope: "Task alias to bounded explicit-source digest; no Confluence expansion.", Evidence: "qualified", Completeness: "per-source", Skill: "jira", Reference: "reference/portfolio-evidence.md"},
	{ID: "jira.portfolio.confluence.section", TaskClass: "jira/portfolio", Service: "confluence", Role: "expand", Priority: 70, Summary: "Return one bounded linked evidence section instead of a full-page view", CLICommand: "conf page section", MCPTool: "confluence_page_section", MCPScope: "One bounded exact section with provenance-dependent page-version gate.", Evidence: "derived", Completeness: "explicit", Skill: "confluence", Reference: "reference/commands.md"},

	{ID: "jira.board-portfolio.fields", TaskClass: "jira/board-portfolio", Service: "jira", Role: "discover", Priority: 10, Summary: "Resolve the narrow custom field used by the board evidence", CLICommand: "jira fields", MCPTool: "jira_fields", MCPScope: "Value-free field catalog/qualification with optional summary-only projection.", Evidence: "identity", Completeness: "explicit", Skill: "jira", Reference: "reference/portfolio-evidence.md"},
	{ID: "jira.board-portfolio.view", TaskClass: "jira/board-portfolio", Service: "jira", Role: "primary", Priority: 20, Summary: "Read one normalized board snapshot for portfolio membership and child state", CLICommand: "jira board view", MCPTool: "jira_board_view", MCPScope: "Task alias to bounded transient normalized board snapshot.", Evidence: "snapshot", Completeness: "explicit", Skill: "jira", Reference: "reference/portfolio-evidence.md"},
	{ID: "jira.board-portfolio.epic.digest", TaskClass: "jira/board-portfolio", Service: "jira", Role: "expand", Priority: 30, Summary: "Qualify only the per-epic field and history evidence absent from the board", CLICommand: "jira epic digest", MCPTool: "jira_epic_digest", MCPScope: "Task alias to bounded explicit-source digest.", Evidence: "qualified", Completeness: "per-source", Skill: "jira", Reference: "reference/portfolio-evidence.md"},

	{ID: "jira.batch.issue.export", TaskClass: "jira/batch-analysis", Service: "jira", Role: "primary", Priority: 10, Summary: "Read an ordered explicit issue selector set without durable artifacts", CLICommand: "jira export", Evidence: "snapshot", Completeness: "explicit", Skill: "jira", Reference: "reference/batch-read.md"},

	{ID: "jira.structure.rows", TaskClass: "jira/structure-planning", Service: "jira", Role: "discover", Priority: 10, Summary: "Read a selected Structure subtree without resolving issue fields", CLICommand: "jira structure rows", Evidence: "snapshot", Completeness: "explicit", Skill: "jira", Reference: "reference/structure-batch.md"},
	{ID: "jira.structure.values", TaskClass: "jira/structure-planning", Service: "jira", Role: "expand", Priority: 20, Summary: "Read an explicit Structure row and attribute value matrix", CLICommand: "jira structure values", Evidence: "snapshot", Completeness: "per-row", Skill: "jira", Reference: "reference/structure-batch.md"},
	{ID: "jira.structure.issue.export", TaskClass: "jira/structure-planning", Service: "jira", Role: "expand", Priority: 30, Summary: "Read an ordered explicit issue batch without durable artifacts", CLICommand: "jira export", Evidence: "snapshot", Completeness: "explicit", Skill: "jira", Reference: "reference/structure-batch.md"},

	{ID: "jira.mirror.snapshot", TaskClass: "jira/mirror", Service: "jira", Role: "inspect", Priority: 10, Summary: "Read exact content-free mirror, baseline, raw snapshot, pending, render, and drift cardinalities", CLICommand: "jira snapshot", MCPTool: "jira_mirror_snapshot", MCPScope: "Fixed-shape content-free offline snapshot at the owner-configured root; no selectable path.", Evidence: "derived", Completeness: "reconciled", Skill: "jira", Reference: "reference/mirror.md"},
	{ID: "jira.issue.fields.edit", TaskClass: "jira/edit", Service: "jira", Role: "discover", Priority: 10, Summary: "Resolve editable custom-field names and current values", CLICommand: "jira issue fields", Evidence: "qualified", Completeness: "explicit", Skill: "jira", Reference: "reference/fields.md"},
	{ID: "jira.issue.field.preview", TaskClass: "jira/edit", Service: "jira", Role: "preview", Priority: 20, Summary: "Build a read-only file-backed custom-field proposal", CLICommand: "jira issue field preview", Evidence: "version-gated", Completeness: "explicit", Skill: "jira", Reference: "reference/fields.md"},
	{ID: "jira.issue.field.set", TaskClass: "jira/edit", Service: "jira", Role: "write", Priority: 30, Summary: "Apply one reviewed custom-field proposal", CLICommand: "jira issue field set", Evidence: "version-gated", Completeness: "reconciled", Skill: "jira", Reference: "reference/fields.md"},
	{ID: "jira.issue.worklog.list", TaskClass: "jira/edit", Service: "jira", Role: "discover", Priority: 40, Summary: "Read the complete worklog baseline before a reviewed add", CLICommand: "jira issue worklog list", Evidence: "snapshot", Completeness: "explicit", Skill: "jira", Reference: "reference/editing.md"},
	{ID: "jira.issue.worklog.add", TaskClass: "jira/edit", Service: "jira", Role: "write", Priority: 50, Summary: "Preview then apply one baseline-bound worklog without replaying an ambiguous write", CLICommand: "jira issue worklog add", Evidence: "hash-bound", Completeness: "reconciled", Skill: "jira", Reference: "reference/editing.md"},
	{ID: "jira.issue.plan.apply", TaskClass: "jira/edit", Service: "jira", Role: "write", Priority: 60, Summary: "Apply a reviewed guarded multi-issue plan", CLICommand: "jira issue plan apply", Evidence: "version-gated", Completeness: "per-row", Skill: "jira", Reference: "reference/commands.md"},

	{ID: "confluence.page.resolve", TaskClass: "confluence/evidence", Service: "confluence", Role: "discover", Priority: 10, Summary: "Resolve page IDs, full URLs, or short links", CLICommand: "conf page resolve", MCPTool: "confluence_page_resolve", MCPScope: "Exact numeric or same-origin reference resolution; no fuzzy match.", Evidence: "identity", Completeness: "exact", Skill: "confluence", Reference: "reference/commands.md"},
	{ID: "confluence.page.meta", TaskClass: "confluence/evidence", Service: "confluence", Role: "discover", Priority: 15, Summary: "Read page identity, revision, update time, and restriction state without page content", CLICommand: "conf page meta", MCPTool: "confluence_page_meta", MCPScope: "Body-free governance projection without labels, ancestors, URLs, principals, or content.", Evidence: "qualified", Completeness: "explicit", Skill: "confluence", Reference: "reference/metadata-comments.md"},
	{ID: "confluence.page.outline", TaskClass: "confluence/evidence", Service: "confluence", Role: "discover", Priority: 20, Summary: "Return a heading inventory without exposing the full rendered page", CLICommand: "conf page outline", MCPTool: "confluence_page_outline", MCPScope: "Bounded completeness-qualified heading inventory.", Evidence: "derived", Completeness: "explicit", Skill: "confluence", Reference: "reference/commands.md"},
	{ID: "confluence.page.section", TaskClass: "confluence/evidence", Service: "confluence", Role: "primary", Priority: 30, Summary: "Read one bounded rendered section by heading", CLICommand: "conf page section", MCPTool: "confluence_page_section", MCPScope: "Bounded exact section with provenance-dependent page-version gate.", Evidence: "derived", Completeness: "explicit", Skill: "confluence", Reference: "reference/commands.md"},
	{ID: "confluence.page.sections", TaskClass: "confluence/evidence", Service: "confluence", Role: "primary", Priority: 35, Summary: "Read ordered bounded sections from one reconciled page snapshot", CLICommand: "conf page sections", MCPTool: "confluence_page_sections", MCPScope: "One-to-32 ordered sections from one revision with aggregate caps.", Evidence: "derived", Completeness: "reconciled", Skill: "confluence", Reference: "reference/commands.md"},
	{ID: "confluence.page.view", TaskClass: "confluence/evidence", Service: "confluence", Role: "expand", Priority: 40, Summary: "Read a transient full Markdown page view", CLICommand: "conf page view", Evidence: "derived", Completeness: "explicit", Skill: "confluence", Reference: "reference/commands.md"},
	{ID: "confluence.attachment.list", TaskClass: "confluence/evidence", Service: "confluence", Role: "expand", Priority: 50, Summary: "List page attachment metadata with explicit inventory completeness", CLICommand: "conf attachment list", MCPTool: "confluence_attachment_list", MCPScope: "Version-gated metadata-only inventory; no bytes, paths, or comments.", Evidence: "qualified", Completeness: "explicit", Skill: "confluence", Reference: "reference/tables-attachments.md"},
	{ID: "confluence.table.summary", TaskClass: "confluence/table-analytics", Service: "confluence", Role: "discover", Priority: 10, Summary: "Inventory table shapes, spans, links, and styles without exposing cell content", CLICommand: "conf table summary", MCPTool: "confluence_table_summary", MCPScope: "Bounded content-free structural summary with page-version evidence.", Evidence: "derived", Completeness: "explicit", Skill: "confluence", Reference: "reference/tables-attachments.md"},
	{ID: "confluence.table.extract", TaskClass: "confluence/table-analytics", Service: "confluence", Role: "primary", Priority: 20, Summary: "Extract one structured table with spans, links, and spreadsheet-safe values", CLICommand: "conf table extract", MCPTool: "confluence_table_extract", MCPScope: "One selected typed table only; no all-table or alternate-format workflow.", Evidence: "derived", Completeness: "explicit", Skill: "confluence", Reference: "reference/tables-attachments.md"},

	{ID: "confluence.pull", TaskClass: "confluence/edit", Service: "confluence", Role: "stage", Priority: 10, Summary: "Mirror native CSF and its versioned Markdown view", CLICommand: "conf pull", Evidence: "version-gated", Completeness: "explicit", Skill: "confluence", Reference: "reference/push.md"},
	{ID: "confluence.mirror.snapshot", TaskClass: "confluence/mirror", Service: "confluence", Role: "inspect", Priority: 15, Summary: "Read exact content-free mirror, baseline, render, validation, and drift cardinalities", CLICommand: "conf snapshot", MCPTool: "confluence_mirror_snapshot", MCPScope: "Fixed-shape content-free offline snapshot at the owner-configured root; no selectable path.", Evidence: "derived", Completeness: "reconciled", Skill: "confluence", Reference: "reference/sync.md"},
	{ID: "confluence.diff", TaskClass: "confluence/edit", Service: "confluence", Role: "review", Priority: 20, Summary: "Inspect offline semantic and byte changes", CLICommand: "conf diff", Evidence: "derived", Completeness: "explicit", Skill: "confluence", Reference: "reference/push.md"},
	{ID: "confluence.plan.create", TaskClass: "confluence/edit", Service: "confluence", Role: "plan", Priority: 30, Summary: "Create a durable review-bound batch update plan", CLICommand: "conf plan create", Evidence: "hash-bound", Completeness: "explicit", Skill: "confluence", Reference: "reference/push.md"},
	{ID: "confluence.plan.preview", TaskClass: "confluence/edit", Service: "confluence", Role: "review", Priority: 40, Summary: "Preflight a plan locally and remotely without writes", CLICommand: "conf plan preview", Evidence: "hash-bound", Completeness: "per-page", Skill: "confluence", Reference: "reference/push.md"},
	{ID: "confluence.plan.apply", TaskClass: "confluence/edit", Service: "confluence", Role: "write", Priority: 50, Summary: "Apply an explicitly confirmed reviewed plan", CLICommand: "conf plan apply", Evidence: "version-gated", Completeness: "per-page", Skill: "confluence", Reference: "reference/push.md"},

	{ID: "knowledge.jira.search", TaskClass: "knowledge/search", Service: "jira", Role: "discover", Priority: 10, Summary: "Search Jira for current topic candidates", CLICommand: "jira issue search", MCPTool: "jira_issue_search", MCPScope: "Task alias to bounded IssueList page; one selector alias and encoded-result cap.", Evidence: "snapshot", Completeness: "explicit", Skill: "search-knowledge", Reference: "SKILL.md"},
	{ID: "knowledge.confluence.search", TaskClass: "knowledge/search", Service: "confluence", Role: "discover", Priority: 20, Summary: "Search Confluence for current topic candidates", CLICommand: "conf search", MCPTool: "confluence_search", MCPScope: "Bounded qualified CQL candidate page without page bodies.", Evidence: "snapshot", Completeness: "explicit", Skill: "confluence", Reference: "reference/commands.md"},
	{ID: "knowledge.jira.field", TaskClass: "knowledge/search", Service: "jira", Role: "expand", Priority: 30, Summary: "Expand one exact selected Jira field", CLICommand: "jira issue field get", MCPTool: "jira_issue_field_get", MCPScope: "Task alias to exact compact field evidence with typed byte bound.", Evidence: "qualified", Completeness: "explicit", Skill: "jira", Reference: "reference/evidence-workflow.md"},
	{ID: "knowledge.confluence.outline", TaskClass: "knowledge/search", Service: "confluence", Role: "expand", Priority: 40, Summary: "Inspect selected-page headings without exposing its full body", CLICommand: "conf page outline", MCPTool: "confluence_page_outline", MCPScope: "Task alias to bounded completeness-qualified heading inventory.", Evidence: "derived", Completeness: "explicit", Skill: "confluence", Reference: "reference/commands.md"},
	{ID: "knowledge.confluence.section", TaskClass: "knowledge/search", Service: "confluence", Role: "expand", Priority: 50, Summary: "Read one bounded selected-page section", CLICommand: "conf page section", MCPTool: "confluence_page_section", MCPScope: "Task alias to bounded exact section with conditional version binding.", Evidence: "derived", Completeness: "explicit", Skill: "confluence", Reference: "reference/commands.md"},
	{ID: "knowledge.confluence.sections", TaskClass: "knowledge/search", Service: "confluence", Role: "expand", Priority: 55, Summary: "Read several selected sections from one bounded page snapshot", CLICommand: "conf page sections", MCPTool: "confluence_page_sections", MCPScope: "Task alias to bounded ordered multi-section projection with aggregate reconciliation.", Evidence: "derived", Completeness: "reconciled", Skill: "confluence", Reference: "reference/commands.md"},
}

// Definitions returns the curated definitions in deterministic catalog order.
// The returned slice is a copy and may be modified by the caller.
func Definitions() []Definition {
	return append([]Definition(nil), definitions...)
}
