package main

import (
	"bytes"
	"errors"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const generatedPreamble = `<!-- Code generated by check-reference-split; DO NOT EDIT. -->

This compatibility index preserves historical heading links. Canonical prose lives only at the linked destinations.

`

func checkReferenceSplit(root, manifestPath string, write bool) (report, error) {
	return checkReferenceSplitWithInventory(root, manifestPath, write, historicalInventory{
		Routes: permanentHistoricalRouteCount, SHA256: permanentHistoricalRouteInventory,
	})
}

func checkReferenceSplitWithInventory(root, manifestPath string, write bool, expected historicalInventory) (report, error) {
	root, err := filepath.Abs(root)
	if err != nil {
		return report{}, fmt.Errorf("resolve repository root: %w", err)
	}
	root = filepath.Clean(root)
	if !filepath.IsAbs(manifestPath) {
		manifestPath = filepath.Join(root, filepath.FromSlash(manifestPath))
	}
	value, err := loadManifest(manifestPath)
	if err != nil {
		return report{}, err
	}
	if err := validateHistoricalInventory(value.Routes, expected); err != nil {
		return report{}, err
	}
	groups, err := validateManifest(root, value)
	if err != nil {
		return report{}, err
	}
	if err := validateDestinations(root, value.Routes); err != nil {
		return report{}, err
	}

	paths := sortedGroupPaths(groups)
	result := report{Indexes: len(paths), Routes: len(value.Routes)}
	for _, legacyPath := range paths {
		rendered, err := renderCompatibilityIndex(legacyPath, groups[legacyPath])
		if err != nil {
			return result, fmt.Errorf("render %s: %w", legacyPath, err)
		}
		path := filepath.Join(root, filepath.FromSlash(legacyPath))
		actual, err := os.ReadFile(path)
		if err != nil {
			return result, fmt.Errorf("read compatibility index %s: %w", legacyPath, err)
		}
		if bytes.Equal(actual, rendered) {
			continue
		}
		if !write {
			return result, fmt.Errorf("compatibility index %q is stale; regenerate it with check-reference-split -write", legacyPath)
		}
		info, err := os.Lstat(path)
		if err != nil || !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 {
			return result, fmt.Errorf("refuse to write non-regular or symlink compatibility index %q", legacyPath)
		}
		if err := os.WriteFile(path, rendered, info.Mode().Perm()); err != nil {
			return result, fmt.Errorf("write compatibility index %s: %w", legacyPath, err)
		}
		result.Written++
	}
	return result, nil
}

func validateDestinations(root string, routes []route) error {
	documents := map[string]markdownDocument{}
	var problems []string
	for _, item := range routes {
		document, ok := documents[item.DestinationPath]
		if !ok {
			contents, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(item.DestinationPath)))
			if err != nil {
				return fmt.Errorf("read canonical destination %s: %w", item.DestinationPath, err)
			}
			document = parseMarkdown(string(contents))
			documents[item.DestinationPath] = document
		}
		if !document.Anchors[item.DestinationAnchor] {
			problems = append(problems, fmt.Sprintf("%s route %d destination %s#%s does not exist case-exactly",
				item.LegacyPath, item.SourceOrder, item.DestinationPath, item.DestinationAnchor))
		}
	}
	if len(problems) != 0 {
		sort.Strings(problems)
		return errors.New("reference split destination validation failed:\n- " + strings.Join(problems, "\n- "))
	}
	return nil
}

func renderCompatibilityIndex(legacyPath string, routes []route) ([]byte, error) {
	if len(routes) == 0 {
		return nil, errors.New("cannot render an empty route list")
	}
	var rendered strings.Builder
	rendered.WriteString(generatedPreamble)
	slugger := newGitHubSlugger()
	legacyAnchors := make([]string, 0, len(routes))
	for index, item := range routes {
		if item.LegacyPath != legacyPath || item.SourceOrder != index+1 {
			return nil, errors.New("routes do not match the legacy path and contiguous source order")
		}
		anchor := slugger.slug(item.HeadingText)
		if anchor == "" {
			return nil, fmt.Errorf("heading %q has no stable legacy anchor", item.HeadingText)
		}
		legacyAnchors = append(legacyAnchors, anchor)
		rendered.WriteString(strings.Repeat("#", item.HeadingLevel))
		rendered.WriteByte(' ')
		rendered.WriteString(item.HeadingText)
		rendered.WriteString("\n\n[Read the canonical section](")
		rendered.WriteString(relativeDestination(legacyPath, item.DestinationPath, item.DestinationAnchor))
		rendered.WriteString(").\n\n")
	}

	// Keep one final newline without adding an otherwise empty trailing line.
	result := []byte(strings.TrimSuffix(rendered.String(), "\n"))
	parsed := parseMarkdown(string(result))
	if len(parsed.Headings) != len(routes) {
		return nil, errors.New("rendered compatibility index does not contain every declared heading exactly once")
	}
	for index, item := range routes {
		actual := parsed.Headings[index]
		if actual.Level != item.HeadingLevel || actual.Text != item.HeadingText || actual.Anchor != legacyAnchors[index] {
			return nil, fmt.Errorf("rendered heading %d does not preserve exact level and text", index+1)
		}
	}
	return result, nil
}

func relativeDestination(legacyPath, destinationPath, anchor string) string {
	relative, err := filepath.Rel(filepath.Dir(filepath.FromSlash(legacyPath)), filepath.FromSlash(destinationPath))
	if err != nil {
		panic("repository-relative Markdown paths must have a relative destination")
	}
	value := &url.URL{Path: filepath.ToSlash(relative), Fragment: anchor}
	return value.String()
}

func sortedGroupPaths(groups map[string][]route) []string {
	paths := make([]string, 0, len(groups))
	for path := range groups {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	return paths
}
