// Command gen-homebrew-formula builds a Homebrew formula (Formula/atl.rb) from
// the cross-compiled binaries in a dist directory, pinning each platform's
// release-asset URL and SHA-256. It is the source-of-truth generator so the
// formula can never drift from the published binaries.
//
//	go run ./scripts/gen-homebrew-formula --dist dist --version 1.2.3 \
//	    --repo isukharev/atl > Formula/atl.rb
//
// It expects binaries named atl-<os>-<arch> in the dist dir (the same names
// `make dist` produces). The tap repository that hosts the formula is created
// and maintained by the project owner; this command only emits the file.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type build struct {
	os, arch, sha256, asset string
}

func main() {
	dist := flag.String("dist", "dist", "directory with atl-<os>-<arch> binaries")
	version := flag.String("version", "", "release version (required, with or without leading v)")
	repo := flag.String("repo", "isukharev/atl", "owner/repo the release assets live under")
	flag.Parse()
	if *version == "" {
		fail("--version is required")
	}

	builds, err := collectBuilds(*dist)
	if err != nil {
		fail(err.Error())
	}
	out, err := renderFormula(strings.TrimPrefix(strings.TrimSpace(*version), "v"), *repo, builds)
	if err != nil {
		fail(err.Error())
	}
	fmt.Print(out)
}

// collectBuilds reads atl-<os>-<arch> binaries from dist and computes each
// SHA-256. It deliberately skips .sha256/manifest/VERSION sidecars.
func collectBuilds(dist string) ([]build, error) {
	entries, err := os.ReadDir(dist)
	if err != nil {
		return nil, err
	}
	var builds []build
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasPrefix(name, "atl-") || strings.ContainsAny(name, ".") {
			continue // skip .sha256, manifest.json, VERSION, dirs
		}
		parts := strings.SplitN(strings.TrimPrefix(name, "atl-"), "-", 2)
		if len(parts) != 2 {
			return nil, fmt.Errorf("unexpected binary name: %s", name)
		}
		sum, err := sha256File(filepath.Join(dist, name))
		if err != nil {
			return nil, err
		}
		builds = append(builds, build{os: parts[0], arch: parts[1], sha256: sum, asset: name})
	}
	return builds, nil
}

// renderFormula emits the Ruby formula. macOS/Linux × arm64/amd64 are mapped to
// Homebrew's on_macos/on_linux + on_arm/on_intel blocks; only platforms present
// in builds are emitted. The single install picks whichever single binary the
// arch-specific url downloaded, renaming it to `atl`.
func renderFormula(version, repo string, builds []build) (string, error) {
	if len(builds) == 0 {
		return "", fmt.Errorf("no atl-<os>-<arch> binaries found")
	}
	byKey := map[string]build{}
	for _, b := range builds {
		byKey[b.os+"/"+b.arch] = b
	}
	tag := "v" + version
	base := fmt.Sprintf("https://github.com/%s/releases/download/%s", repo, tag)

	var b strings.Builder
	fmt.Fprintf(&b, "# typed: false\n# frozen_string_literal: true\n\n")
	fmt.Fprintf(&b, "# Homebrew formula for atl — GENERATED by scripts/gen-homebrew-formula.\n")
	fmt.Fprintf(&b, "# Do not edit by hand; regenerate with `make homebrew` on each release and\n")
	fmt.Fprintf(&b, "# copy this file into the tap repository (Formula/atl.rb).\n")
	fmt.Fprintf(&b, "class Atl < Formula\n")
	fmt.Fprintf(&b, "  desc \"Git-style CLI for Confluence & Jira, built for coding agents\"\n")
	fmt.Fprintf(&b, "  homepage \"https://github.com/%s\"\n", repo)
	fmt.Fprintf(&b, "  version %q\n", version)
	fmt.Fprintf(&b, "  license \"Apache-2.0\"\n")

	osBlocks := []struct{ hb, dist string }{{"on_macos", "darwin"}, {"on_linux", "linux"}}
	archBlocks := []struct{ hb, dist string }{{"on_arm", "arm64"}, {"on_intel", "amd64"}}
	for _, ob := range osBlocks {
		// Only open an os block if at least one of its arches is present.
		present := false
		for _, ab := range archBlocks {
			if _, ok := byKey[ob.dist+"/"+ab.dist]; ok {
				present = true
			}
		}
		if !present {
			continue
		}
		fmt.Fprintf(&b, "\n  %s do\n", ob.hb)
		for _, ab := range archBlocks {
			bd, ok := byKey[ob.dist+"/"+ab.dist]
			if !ok {
				continue
			}
			fmt.Fprintf(&b, "    %s do\n", ab.hb)
			fmt.Fprintf(&b, "      url \"%s/%s\"\n", base, bd.asset)
			fmt.Fprintf(&b, "      sha256 %q\n", bd.sha256)
			fmt.Fprintf(&b, "    end\n")
		}
		fmt.Fprintf(&b, "  end\n")
	}

	fmt.Fprintf(&b, "\n  def install\n")
	fmt.Fprintf(&b, "    bin.install Dir[\"atl-*\"].first => \"atl\"\n")
	fmt.Fprintf(&b, "  end\n")
	fmt.Fprintf(&b, "\n  test do\n")
	fmt.Fprintf(&b, "    assert_match version.to_s, shell_output(\"#{bin}/atl version\")\n")
	fmt.Fprintf(&b, "  end\n")
	fmt.Fprintf(&b, "end\n")
	return b.String(), nil
}

func sha256File(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:]), nil
}

func fail(msg string) {
	fmt.Fprintln(os.Stderr, "gen-homebrew-formula:", msg)
	os.Exit(1)
}
